routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::resource('home', 'HomeController');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    //
    protected $fillable = ['title',
        'description',
        'article',
        'rank',
        'image_name',
        'image_path',
        'article_date'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $table = 'articles';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
use Illuminate\Support\Collection;
use Carbon\Carbon;

class ArticleController extends Controller
{
    public function index()
    {
        $dates = Article::select('article_date')->distinct()->get();

        $feed = [];
        foreach($dates as $dute){
            $articles = Article::where('article_date', $dute->article_date)->get();
            $dt = Carbon::parse($dute->article_date);

            $feed[]=[
                'date' => $dt->timestamp,
                'articles' => $articles
            ];
        }
        // return Article::orderBy('article_date','desc')->get();
        return $feed;
    }
 
    public function show($date)
    {
        return Article::where('article_date',$date)->get();
    }

    public function order()
    {
        $dates = Article::select('article_date')->orderBy('article_date','desc')->distinct()->get();
        $duted = [];
        foreach($dates as $dt){
            $ts = Carbon::parse($dt->article_date);

            $duted[]=[
                'article_date' => $ts->timestamp
            ];
        }
        return $duted;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
use Alert;
use Exception;
use Illuminate\Support\Facades\Storage;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::orderBy('article_date','desc')->paginate(15);
        return view('home.index')
         ->with('articles', $articles);
    }

    public function create(){
        // $current_time = Carbon::now();
        // $old_time = Carbon::createFromTimestamp(Cache::store('articleDate')->get('date'));
        // if($current_time->diffInWeeks($old_time) > 3){
        //   Cache::store('articleDate')->put($current_time->timestamp);  
        // }
        return view('home.create');
    }


    public function store(Request $request){
        //validate
        $validatedData = $this->validate(request(),[
            'article_date'     => 'bail|required|date',
            'rank'        => 'bail|required|numeric',
            'title'       => 'required',
            'article'     => 'required',
            'description' => 'bail|required|max:500',
            'image'       => 'bail|nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        try{
            $article = new Article($request->input());

            if($request->hasFile('image')){
                $file = $request->file('image');
//                Storage::putFile('public/thumbnails', $file);
                $request->file('image')->store('public/thumbnails');
                $article->image_path = asset(Storage::url('thumbnails/'.$file->hashName()));
                $article->image_name = $file->hashName();
            }
            $article->save();
            Alert::success('Article saved successfully', 'Success');
        }catch (Exception $exception){
            Alert::error('Article not saved. Please try again', 'Error');
        }
        return back();
    }

    public function show($id){
        $article = Article::find($id);
        return view('home.show')
            ->with('article', $article);
    }

    public function edit($id){
        $article = Article::find($id);
        return view('home.edit')
            ->with('article', $article);
    }

    public function update($id, Request $request){
//        print_r($_POST);
//        die();
        //validate
        $validatedData = $this->validate(request(),[
            'article_date'     => 'bail|required|date',
            'rank'        => 'bail|required|numeric',
            'title'       => 'required',
            'article'     => 'required',
            'description' => 'bail|required|max:500',
            'image'       => 'bail|nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        try{
            $article = Article::find($id);

            if($request->hasFile('image')){
                //delete old file
                //check if exists first
                if (isset($article->image_name) && !trim($article->image_name)===''){
                    Storage::delete('public/thumbnails/'.$article->image_name);
//                unlink($article->image_path);

                    //store new file
                    $file = $request->file('image');
                    $request->file('image')->store('public/thumbnails');
                    $article->image_path = asset(Storage::url('thumbnails/'.$file->hashName()));
                    $article->image_name = $file->hashName();
                }else{
                    $file = $request->file('image');
//                Storage::putFile('public/thumbnails', $file);
                    $request->file('image')->store('public/thumbnails');
                    $article->image_path = asset(Storage::url('thumbnails/'.$file->hashName()));
                    $article->image_name = $file->hashName();
                }
            }
            $article->title = $request->title;
            $article->article_date = $request->article_date;
            $article->rank = $request->rank;
            $article->article = $request->article;
            $article->description = $request->description;
            $article->save();
            Alert::success('Article edited successfully', 'Success');
        }catch (Exception $exception){
            Alert::error('Article not edited. Please try again', 'Error');
        }

        return redirect('home');
    }

    public function destroy($id)
    {
        try{
            $article = Article::find($id);
            if($this->isNotEmpty($article->image_name)){
                Storage::delete('public/thumbnails/'.$article->image_name);
            }
            $article->delete();
            \Session::flash('message', 'Successfully deleted the article!');
//            Alert::success('Article deleted successfully', 'Success');
        }catch (Exception $exception){
            Alert::error('Article not deleted. Please try again', 'Error');
        }

        return redirect('home');
    }

    function isNotEmpty($input){
        $strTemp = $input;
        $strTemp = trim($strTemp);

        if($strTemp !== '')
        {
            return true;
        }

        return false;
    }
}

resources/views/home/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a class="btn btn-info" style="margin-bottom: .5em;" href="{{route('home.index')}}">Return to home</a>
            <div class="panel panel-info">
                <div class="panel-heading">Please fill out the form below to add a new article</div>

                <div class="panel-body">

                    @if (\Session::has('success'))
                        <div class="alert alert-success">
                            <p>{{ \Session::get('success') }}</p>
                        </div><br />
                    @endif

                    <form class="form" role="form" enctype="multipart/form-data" method="post" action="{{route('home.store')}}" >
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('article_date') ? ' has-error' : '' }}">
                            <label for="article_date" class="pushDown col-sm-4 control-label">Article Date</label>

                            <div class="pushDown col-md-8">
                                <input id="article_date" type="date" class="form-control" name="article_date" value="{{ old('article_date') }}" required autofocus>

                                @if ($errors->has('article_date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('article_date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('rank') ? ' has-error' : '' }}">
                            <label for="rank" class="pushDown col-sm-4 control-label">Article Number</label>

                            <div class="pushDown col-md-8">
                                <input id="rank" type="number" min="1" class="form-control" name="rank" value="{{ old('rank') }}" required autofocus>

                                @if ($errors->has('rank'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('rank') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="pushDown col-sm-4 control-label">Title</label>

                            <div class="pushDown col-md-8">
                                <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" required autofocus>

                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="pushDown col-sm-4 control-label">Description (30 words min)</label>

                            <div class="pushDown col-md-8">
                                <input id="description" type="text" class="form-control" name="description" value="{{ old('description') }}" required>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                            <label for="image" class="pushDown col-sm-4 control-label">Thumbnail Image</label>

                            <div class="pushDown col-md-8">
                                <label class="custom-file">
                                    <input id="image" type="file" value="{{ old('image') }}" class="custom-file-input form-control-file" name="image" accept="image/*">
                                    <span class="custom-file-control"></span>
                                </label>


                                @if ($errors->has('image'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('article') ? ' has-error' : '' }}">
                            <label for="article" class="pushDown col-md-4 control-label">Article</label>

                            <div class="pushDown col-md-8">
                                <textarea id="article" class="form-control tinyMad" rows="20" name="article">{{ old('article') }}</textarea>

                                @if ($errors->has('article'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('article') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit the article
                                </button>

                                {{--  <a class="btn btn-link" href="{{ route('password.request') }}">
                                    Forgot Your Password?
                                </a>  --}}
                            </div>
                        </div> 
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/home/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <a class="btn btn-info" style="margin-bottom: .5em;" href="{{route('home.index')}}">Return to home</a>
                <div class="panel panel-primary">
                    <div class="panel-heading">Please edit the form below to edit the article</div>

                    <div class="panel-body">

                        {{--@if (\Session::has('success'))--}}
                            {{--<div class="alert alert-success">--}}
                                {{--<p>{{ \Session::get('success') }}</p>--}}
                            {{--</div><br />--}}
                        {{--@endif--}}

                        <form class="form" role="form" enctype="multipart/form-data" method="POST" action="{{route('home.update', ['id' => $article->id])}}" >
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="PUT">

                            <div class="form-group{{ $errors->has('article_date') ? ' has-error' : '' }}">
                                <label for="article_date" class="pushDown col-md-4 control-label">Article Date</label>

                                <div class="pushDown col-md-8">
                                    <input id="article_date" type="date" class="form-control" name="article_date" value="{{\Carbon\Carbon::parse($article->article_date)->format('Y-m-d')}}" required autofocus>

                                    @if ($errors->has('article_date'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('article_date') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('rank') ? ' has-error' : '' }}">
                                <label for="rank" class="pushDown col-md-4 control-label">Article Number</label>

                                <div class="pushDown col-md-8">
                                    <input id="rank" type="number" min="1" class="form-control" name="rank" value="{{$article->rank}}" required autofocus>

                                    @if ($errors->has('rank'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('rank') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label for="title" class="pushDown col-md-4 control-label">Title</label>

                                <div class="pushDown col-md-8">
                                    <input id="title" type="text" class="form-control" name="title" value="{{$article->title}}" required autofocus>

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label for="description" class="pushDown col-md-4 control-label">Description (At least 30 words)</label>

                                <div class="pushDown col-md-8">
                                    <input id="description" type="text" class="form-control" name="description" value="{{$article->description}}" required>

                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                                <label for="image" class="pushDown col-md-4 control-label">Thumbnail Image</label>


                                <div class="pushDown col-md-8">
                                    <img class="thumbnail" style="max-height: 7em; max-width: 7em" src="{{$article->image_path}}"/>
                                    <label class="custom-file">
                                        <input id="image" type="file" value="{{ old('image') }}" class="custom-file-input form-control-file" name="image" accept="image/*">
                                        <span class="custom-file-control"></span>
                                    </label>


                                    @if ($errors->has('image'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('article') ? ' has-error' : '' }}">
                                <label for="article" class="pushDown col-md-4 control-label">Article</label>

                                <div class="pushDown col-md-8">
                                    <textarea id="article" class="form-control tinyMad" rows="20" name="article">{{$article->article}}</textarea>

                                    @if ($errors->has('article'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('article') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Update the article
                                    </button>

                                    {{--  <a class="btn btn-link" href="{{ route('password.request') }}">
                                        Forgot Your Password?
                                    </a>  --}}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/home/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <div class="panel panel-default">
                {{--  <div class="panel-heading">What would you like to do today?</div>  --}}

                <div class="panel-body">
                    <div class="clearfix"></div>
                    <div class="left">
                        <a class="btn btn-primary" href="{{route('home.create')}}">
                            Add a new newsletter
                        </a>
                    </div>

                    {{--  <div class="left">
                        <a class="btn btn-primary" href="{{route('editnews')}}">
                            Edit newsletters
                        </a>
                    </div>  --}}
                    <div class="clearfix"></div>

                    <!-- will be used to show any messages -->
                    @if (Session::has('message'))
                        <div class="alert alert-info">{{ Session::get('message') }}</div>
                    @endif

                    <div class="clearfix"></div>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Article Date</th>
                                <th>Title</th>
                                <th>Description</th>
                                {{--<th>Article</th>--}}
                                {{--<th>Image Path</th>--}}

                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($articles as $key => $value)
                            <tr>
                                <td>{{\Carbon\Carbon::parse($value->article_date)->format('d-M-Y')}}</td>
                                <td>{{$value->title}}</td>
                                <td>{{str_limit($value->description,100)}}</td>
{{--                                <td>{{str_limit($value->article,20)}}</td>--}}
{{--                                <td>{{str_limit($value->image_path,10)}}</td>--}}

                                <!-- we will also add show, edit, and delete buttons -->
                                <td>


                                    <!-- show the nerd (uses the show method found at GET /nerds/{id} -->
                                    <a class="btn btn-small btn-success" href="{{route('home.show', ['id' => $value->id])}}" title="Show"><i class="fas fa-eye"></i></a>

                                    <!-- edit this nerd (uses the edit method found at GET /nerds/{id}/edit -->
                                    <a class="btn btn-small btn-info" href="{{route('home.edit', ['id' => $value->id])}}" title="Edit"><i class="fas fa-edit"></i></a>

                                    <!-- delete the nerd (uses the destroy method DESTROY /nerds/{id} -->
                                    <!-- we will add this later since its a little more complicated than the other two buttons -->
                                    <form class="form" role="form" method="POST" action="{{route('home.destroy', ['id' => $value->id])}}" >
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button type="submit" class="btn btn-small btn-danger" title="Delete"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $articles->links() }}
                   
                </div>
                
            </div>
        </div>
    </div>
    
</div>
@endsection

resources/views/home/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <a class="btn btn-info" style="margin-bottom: .5em;" href="{{route('home.index')}}">Return to home</a>
                <div class="panel panel-default">
                    {{--  <div class="panel-heading">What would you like to do today?</div>  --}}

                    <div class="panel-body">
                        <h2>Showing article {{$article->rank}} added on {{\Carbon\Carbon::parse($article->article_date)->format('d-M-Y')}}</h2>
                        <div>
                           <h3>{{$article->title}}</h3>
                            <h4>{{$article->description}}</h4>
                            <div class="clearfix"></div>
                            <img class="thumbnail" style="max-height: 12em; max-width: 12em" src="{{$article->image_path}}"/>
                            <div class="clearfix"></div>
                            <h5>{!! $article->article !!}</h5>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
@endsection